name: Python Formatting, Linting, and Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches: -main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          python -m pip install poetry==1.5.1

      - name: Regenerate lock file
        run: poetry lock --no-update

      - name: Configure Poetry
        run: |
          python -m poetry config virtualenvs.in-project true

      - name: Cache virtualenv
        uses: actions/cache@v3.3.2
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install

      - name: Lint job
        run: |
          # runs black, isort and ruff as defined in pyproject.toml
          poetry run poe format_and_lint

      - name: Run tests with PyTest
        run: |
          poetry run pytest
